# Ejemplos y aclaraciones:

In [1]:
import pandas as pd 
import numpy as np

In [2]:
L1 = list(range(10))
L1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L2 = [0,1,2,3,4,5,6,7,8,9]
L2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L3 = ['a','b','c','d']
L3

['a', 'b', 'c', 'd']

In [5]:
L3[0]

'a'

In [6]:
L3[2]

'c'

In [7]:
L3[2] = 'w'
L3

['a', 'b', 'w', 'd']

In [8]:
T = tuple(range(10))
T

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [9]:
T[0]

0

In [10]:
T[0]='w'

TypeError: 'tuple' object does not support item assignment

In [11]:
T = (1,2,3,3,3,3,3,'setting',2.5,['l1','l2'])
print(type(T))
T

<class 'tuple'>


(1, 2, 3, 3, 3, 3, 3, 'setting', 2.5, ['l1', 'l2'])

In [13]:
T[9][0]='l1_modificado'
T

(1, 2, 3, 3, 3, 3, 3, 'setting', 2.5, ['l1_modificado', 'l2'])

In [14]:
T

(1, 2, 3, 3, 3, 3, 3, 'setting', 2.5, ['l1_modificado', 'l2'])

In [15]:
T2 = (1,2,3,3,3,3,3,'setting',2.5,('l1','l2'))
print(type(T))
T

<class 'tuple'>


(1, 2, 3, 3, 3, 3, 3, 'setting', 2.5, ['l1_modificado', 'l2'])

In [16]:
T2[9][0]='l1_modificado'

TypeError: 'tuple' object does not support item assignment

In [17]:
import numpy as np
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
Npa[0]

0

In [19]:
Npa[0]='w'

ValueError: invalid literal for int() with base 10: 'w'

In [20]:
Npa[0]=38

In [21]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
Np_relleno = np.full(10,25)
Np_relleno

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [45]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
Np_random_dimensiones = np.random.randint(10, size=(3, 5))
Np_random_dimensiones

array([[0, 7, 2, 7, 3],
       [4, 3, 9, 0, 5],
       [4, 4, 6, 0, 5]])

In [48]:
# Verificando el tipo de dato de array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [50]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
print(arr)

<U6
['apple' 'banana' 'cherry']


In [52]:
arr[0]='melon'
print(arr)

['melon' 'banana' 'cherry']


In [54]:
arr[0]=2.8
print(arr)

['2.8' 'banana' 'cherry']


In [57]:
arr[0]*2.0

TypeError: can't multiply sequence by non-int of type 'float'

In [58]:
arr[0]==2.8

False

In [59]:
arr[0]=='2.8'

True

In [60]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [63]:
type(arr[0])

numpy.bytes_

In [64]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr);print(arr.dtype)

[1 2 3 4]
int32


In [65]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [66]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [71]:
print(Np_cero)
Np_cero.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(10,)

In [67]:
Np_cero.ndim

1

In [69]:
print(Np_random_dimensiones)
Np_random_dimensiones.ndim

[[0 7 2 7 3]
 [4 3 9 0 5]
 [4 4 6 0 5]]


2

In [70]:
print(Np_random_dimensiones)
Np_random_dimensiones.shape

[[0 7 2 7 3]
 [4 3 9 0 5]
 [4 4 6 0 5]]


(3, 5)

In [ ]:
Np_random_dimensiones.size

12

In [72]:
Np_cero.dtype

dtype('float64')

In [73]:
Np_cero_int.dtype

dtype('int64')

In [77]:
print(Np_random_dimensiones.itemsize)
print(Np_random_dimensiones.nbytes)

8
120


In [ ]:
Np_cero.nbytes

80

In [ ]:
Np_cero_int.nbytes

80

In [ ]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[0]

1

In [ ]:
Np_diez_numeros[4]

5

In [ ]:
Np_diez_numeros[-1]

10

In [ ]:
Np_diez_numeros[-2]

9

In [ ]:
Np_random_dimensiones

array([[3, 9, 2, 9],
       [6, 2, 3, 1],
       [1, 8, 8, 3]])

In [ ]:
Np_random_dimensiones[2, 1]

8

In [ ]:
Np_diez_numeros[:4]

array([1, 2, 3, 4])

In [ ]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [ ]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [ ]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

In [ ]:
Np_random_dimensiones[2,]

array([1, 8, 8, 3])

In [78]:
print(Np_random_dimensiones)
Np_random_dimensiones[:2, :2]

[[0 7 2 7 3]
 [4 3 9 0 5]
 [4 4 6 0 5]]


array([[0, 7],
       [4, 3]])

In [ ]:
Np_random_dimensiones[2, 3]

3

In [79]:
np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [80]:
#Cuidado, la cantidad de elementos tiene que coincidir al hacer el reshape
#8x5 = 40 != 64

np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,5)
Ajedrez_64

ValueError: cannot reshape array of size 64 into shape (8,5)

In [87]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
print(Array_1.shape)
Arrays_concatenados = np.concatenate([Array_1, Array_2], axis = 0)
print(Arrays_concatenados)
print(Arrays_concatenados.shape)

(5,)
[2 5 8 3 7 8 4 0 0 6]
(10,)


In [85]:
Array_1.reshape(5,1)

array([[6],
       [8],
       [7],
       [0],
       [1]])

In [86]:
Arrays_concatenados = np.concatenate([Array_1.reshape(5,1), Array_2.reshape(5,1)], axis = 1)
print(Arrays_concatenados)
print(Arrays_concatenados.shape)

[[6 9]
 [8 9]
 [7 0]
 [0 6]
 [1 1]]
(5, 2)


In [89]:
Array_extra = np.array([[10],[20]])
print(Array_extra.shape)
Array_extra

(2, 1)


array([[10],
       [20]])

In [91]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
print(Array_apilados_v.shape)
Array_apilados_v

(4, 1)


array([[10],
       [20],
       [10],
       [20]])

In [92]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
print(Array_apilados_h.shape)
Array_apilados_h

(2, 2)


array([[10, 10],
       [20, 20]])

In [ ]:
Arrays_concatenados

array([1, 6, 7, 2, 0, 4, 4, 0, 7, 6])

In [ ]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([1, 6]), array([7, 2, 0, 4, 4, 0, 7, 6])]

In [ ]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])
Array_partido_2

[array([1, 6]), array([7, 2, 0, 4, 4, 0]), array([7, 6])]

In [ ]:
Parte_1, Parte_2, Parte_3 = Array_partido_2
Parte_1

array([1, 6])

In [ ]:
Parte_2

array([7, 2, 0, 4, 4, 0])

In [ ]:
Parte_3

array([7, 6])

In [94]:
print(Ajedrez_64.shape)

(8, 8)


In [95]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [2])
Ajedrez_partido_1

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]]),
 array([[ 3,  4,  5,  6,  7,  8],
        [11, 12, 13, 14, 15, 16],
        [19, 20, 21, 22, 23, 24],
        [27, 28, 29, 30, 31, 32],
        [35, 36, 37, 38, 39, 40],
        [43, 44, 45, 46, 47, 48],
        [51, 52, 53, 54, 55, 56],
        [59, 60, 61, 62, 63, 64]])]

In [97]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [3])
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [100]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)
print(promedio)

[8 3 9 5 7 5 8 7 8 8]
6.8


In [ ]:
Array_aleatorio.sum()

27

In [ ]:
Array_aleatorio.mean()

2.7

In [ ]:
Array_aleatorio.max()

6

In [ ]:
np.median(Array_aleatorio)

2.5

In [ ]:
np.std(Array_aleatorio)

1.7916472867168918

In [ ]:
np.var(Array_aleatorio)

3.21

In [ ]:
Array_1

array([1, 6, 7, 2, 0])

In [ ]:
Array_2


array([4, 4, 0, 7, 6])

In [ ]:
Array_1+5

array([ 6, 11, 12,  7,  5])

In [ ]:
Array_1 + Array_2

array([ 5, 10,  7,  9,  6])

In [ ]:
np.add(Array_1, Array_2)

array([ 5, 10,  7,  9,  6])

In [ ]:
np.matmul(Array_1, Array_2)

42